services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "your-start-command-here"
